name: CI

on: [push, pull_request]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout zero-jetpack
        uses: actions/checkout@v2
        with:
          path: zero-jetpack
      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: master
      - name: Build
        run: zig build -Doptimize=ReleaseFast
        working-directory: zero-jetpack
      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v3
      - name: Upload Artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v1
        with:
          path: "zero-jetpack/zig-out"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2


